-- Expand series/set enums from Pokellector mapping (packages/shared/src/series-sets.ts)

DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Mega Evolution'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Scarlet & Violet'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Sword & Shield'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Sun & Moon'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'XY'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Black & White'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Black & White Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Call of Legends'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'HeartGold SoulSilver'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Platinum'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Nintendo Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Diamond & Pearl'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'EX Ruby & Sapphire'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'e-Card'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Legendary Collection'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Neo Genesis'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Topps Chrome'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Gym Heroes'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Base Set'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'akkNERDS Exclusive'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Illustration Collection'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSeries" ADD VALUE 'Protection'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE '30th Celebration (English)'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Pitch Black'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Chaos Rising'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Perfect Order'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Ascended Heroes'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Phantasmal Flames'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Mega Evolution'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Mega Evolution Energies'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Mega Evolution Black Star Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'White Flare'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Black Bolt'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Destined Rivals'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Journey Together'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Dragon Discovery'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Prismatic Evolutions'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Surging Sparks'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Stellar Crown'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Holiday Calendar 2024'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Trick or Trade 2024'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Shrouded Fable'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Twilight Masquerade'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Temporal Forces'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Paldean Fates'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Paradox Rift'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Scarlet & Violet - 151'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE '151'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Holiday Calendar 2023'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Trick or Trade 2023'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Match Battle 2023'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Obsidian Flames'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Paldea Evolved'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Scarlet & Violet Energies'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Scarlet & Violet'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Scarlet & Violet Base'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Scarlet & Violet Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Crown Zenith'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Crown Zenith - Galarian Gallery'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Silver Tempest'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Silver Tempest - Trainer Gallery'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Lost Origin'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Lost Origin - Trainer Gallery'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Holiday Calendar 2022'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Trick or Trade'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Match Battle'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Pokemon Go'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Astral Radiance'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Astral Radiance - Trainer Gallery'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Brilliant Stars'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Brilliant Stars - Trainer Gallery'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Fusion Strike'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Celebrations'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Evolving Skies'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Chilling Reign'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Battle Styles'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Shining Fates'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s 25th Anniversary'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Vivid Voltage'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Champion''s Path'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Pokemon Futsal Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Darkness Ablaze'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Rebel Clash'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Sword & Shield'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Sword & Shield Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Cosmic Eclipse'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Collection (2019 FR)'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Collection (2019)'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Hidden Fates'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Unified Minds'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Unbroken Bonds'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Detective Pikachu'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Team Up'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Lost Thunder'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Collection (2018)'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Dragon Majesty'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Celestial Storm'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Forbidden Light'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Ultra Prism'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Crimson Invasion'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Shining Legends'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Burning Shadows'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Collection (2017)'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Guardians Rising'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Sun & Moon Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Sun & Moon'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Evolutions'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Collection (2016)'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Steam Siege'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Fates Collide'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Generations'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'BREAKPoint'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Collection (2015)'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'XY BREAKthrough'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Ancient Origins'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Roaring Skies'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Double Crisis'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Primal Clash'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Phantom Forces'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Furious Fists'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Collection (2014)'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'XY Flashfire'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Kalos Starter Set'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'XY Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'XY'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Radiant Collection'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Legendary Treasures'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Plasma Blast'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Plasma Freeze'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Plasma Storm'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Boundaries Crossed'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Dragon Vault'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Dragons Exalted'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Dark Explorers'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Next Destinies'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Noble Victories'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Emerging Powers'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Black & White'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Collection (2013)'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Collection (2012)'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'McDonald''s Collection (2011)'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Black & White Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Call of Legends'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'HS Triumphant'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'HS Undaunted'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'HS Unleashed'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'HeartGold SoulSilver Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'HeartGold SoulSilver'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Pokemon Rumble'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Platinum - Arceus'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Platinum - Supreme Victors'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Platinum - Rising Rivals'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Platinum'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'POP Series 9'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'POP Series 8'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'POP Series 7'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'POP Series 6'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'POP Series 5'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'POP Series 4'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'POP Series 3'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'POP Series 2'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'POP Series 1'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Nintendo Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Stormfront'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Legends Awakened'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Majestic Dawn'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Great Encounters'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Secret Wonders'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Mysterious Treasures'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'DP Black Star Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Diamond & Pearl'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Power Keepers'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Dragon Frontiers'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Crystal Guardians'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Holon Phantoms'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Legend Maker'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Delta Species'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Unseen Forces Unown Collection'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Unseen Forces'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Emerald'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Deoxys'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Team Rocket Returns'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX FireRed & LeafGreen'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Hidden Legends'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Team Magma vs Team Aqua'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Dragon'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Sandstorm'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'EX Ruby & Sapphire'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Skyridge'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Aquapolis'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Best of Game'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Expedition'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Legendary Collection'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Neo Destiny'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Neo Revelation'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Southern Islands'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Neo Discovery'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Neo Genesis'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Topps Series 3'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Topps Series 2'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Topps Series 1'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Gym Challenge'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Gym Heroes'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Team Rocket'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Base Set 2'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Fossil'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Wizards of the Coast Promos'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Jungle'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Base Set'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Mixed'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'First Partner series 2'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'First Partner series 1'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "ProductSet" ADD VALUE 'Accessories'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
